# github/workflows/deploy.yml

name: Deploy Laravel Izolda-Rally.ru

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IZOLDARALLYRU_HOST }}
          username: ${{ secrets.SSH_IZOLDARALLYRU_USERNAME }}
          key: ${{ secrets.SSH_IZOLDARALLYRU_PRIVATE_KEY }}
          script: |
            cd www
            set -e
            echo "Deploying..."
            git pull origin master
            php artisan down
            php composer.phar install
            php artisan migrate --force
            php artisan config:cache
            php artisan event:cache
            php artisan route:cache
            php artisan view:cache
            php artisan up
            echo "Done!"