# github/workflows/deploy.yml

name: Deploy Laravel Izolda-Rally.ru

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IZOLDARALLYRU_HOST }}
          username: ${{ secrets.SSH_IZOLDARALLYRU_USERNAME }}
          key: ${{ secrets.SSH_IZOLDARALLYRU_PRIVATE_KEY }}
          script: |
            cd www
            set -e
            echo "Deploying..."
            git pull origin master
            php artisan down
            php composer.phar install
            php artisan key:generate
            php artisan storage:link
            php artisan migrate:fresh --force
            php artisan optimize:clear
            php artisan up
            echo "Done!"



# php artisan down
# php composer.phar install
# php artisan storage:link
# php artisan migrate:fresh --force
# php artisan install
# php artisan db:seed
# php artisan optimize:clear
# php artisan up
# echo "Done!"

# php artisan config:clear
# php artisan cache:clear
# php artisan event:clear
# php artisan route:clear
# php artisan view:clear
# php artisan config:cache
# php artisan event:cache
# php artisan route:cache
# php artisan view:cache

# php artisan optimize